video:
  ffmpeg: ffmpeg
  ffprobe: ffprobe
  temp_folder: /tmp/webm_haus

spring:
  data:
    cassandra:
      keyspace-name: webmhaus_keyspace


endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false
